#!/usr/bin/python3

import argparse, signal, sys
from wd_daemon import daemon
from wd_client import client

#TODO: List of ports to use in succession in case of collisions?
DEFAULT_PORT = 7877
DEFAULT_SERVER = "taurine.csclub.uwaterloo.ca"

def handler():
    sys.exit(0)

def main():
    signal.signal(signal.SIGTERM, handler)
    parser = argparse.ArgumentParser("Seamlessly monitor processes...")

    group = parser.add_mutually_exclusive_group()
    group.add_argument("-d", "--daemon", action="store_true", help="Run watchdog daemon.")
    group.add_argument("-s", "--server", help="Hostname of watchdog server to use.")

    parser.add_argument("COMMAND", nargs='*', help="The command to be watched. Ignored if running daemon.", type=str)
    parser.add_argument("-p", "--port", help="Port to target on server, or in the case of server, port to listen on.", type=int)
    parser.add_argument("--delay", help="Number of seconds to wait before initially contacting watchdog server.", type=int)

    args = parser.parse_args()

    if args.daemon:
        daemon(port=DEFAULT_PORT)
    else:
        client(server=DEFAULT_SERVER, target_port=DEFAULT_PORT)

if __name__ == '__main__':
    main()
