#!/usr/bin/python

import argparse, signal, sys
from wd_daemon import daemon as exec_daemon
from wd_client import client
import daemon
import socket
import watchdog_pb2
import pwd
import os

#TODO: List of ports to use in succession in case of collisions?
DEFAULT_PORT = 7877
DEFAULT_SERVER = "taurine.csclub.uwaterloo.ca"
DEFAULT_HEARTRATE = 60

def beat(signature, server=DEFAULT_SERVER, port=DEFAULT_PORT):
    hb = watchdog_pb2.Beat()
    hb.signature = signature

    s = socket.socket(socket.AF_INET)
    s.connect((server,port))
    s.send(hb.SerializeToString())
    s.close

def handler(signum, frame):
    print("exiting")
    sys.exit(0)

def main():
    signal.signal(signal.SIGTERM, handler)
    parser = argparse.ArgumentParser("Seamlessly monitor processes...")

    group = parser.add_mutually_exclusive_group()
    group.add_argument("-d", "--daemon", action="store_true", help="Run watchdog daemon.")
    group.add_argument("-s", "--server", default=DEFAULT_SERVER, help="Hostname of watchdog server to use.")

    parser.add_argument("COMMAND", nargs=argparse.REMAINDER, help="The command to be watched. Ignored if running daemon.", type=str)
    parser.add_argument("-p", "--port", default=DEFAULT_PORT, help="Port to target on server, or in the case of server, port to listen on.", type=int)
    parser.add_argument("--delay", default=0, help="Number of seconds to wait before initially contacting watchdog server.", type=int)
    parser.add_argument("-r", "--heartrate", default=DEFAULT_HEARTRATE, help="Number of seconds between heartbeats.", type=int)
    parser.add_argument("--dumpdir", default="/tmp", help="Directory to dump state files to upon request.", type=str)
    parser.add_argument("--signature", help="Force use of a particular signature string.", type=str)

    args = parser.parse_args()

    if args.daemon:
        with daemon.DaemonContext():
            exec_daemon(port=DEFAULT_PORT, dumpdir=args.dumpdir)
    elif args.signature:
        try:
            beat(signature=args.signature)
        except:
            raise
    else:
        client(server=args.server, target_port=args.port, command=args.COMMAND, delay=args.delay, heartrate=args.heartrate)

if __name__ == '__main__':
    main()
